import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Wrapper from "@/components/Wrapper";
import "./globals.css";
import { getServerSession } from "next-auth";

export const metadata = {
  title: "Travel Buddy",
  description: "Generated by Travel Buddy",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  console.log("session", session);

  return (
    <html lang="en">
      <body className="relative bg-gray-100">
        <Wrapper session={session}>
          <Navbar />
          {children}
          <Footer />
        </Wrapper>
      </body>
    </html>
  );
}
