import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ReactQueryClientProvider from "@/components/Wrapper";
import "./globals.css";

export const metadata = {
  title: "Travel Buddy",
  description: "Generated by create Travel Buudy",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[whitesmoke]">
        <ReactQueryClientProvider>
          <Navbar />
          {children}
          <Footer />
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
